### ISSUE TITLE
1.20.1 crashes when running the deobfuscated version generated by Repacker

### ISSUE THREAD

**Issue by TalonFloof** [Fox2Code/Repacker#3]
When deobfuscating 1.20.1 using Repacker version 1.4.0, you'll encounter the following error while trying to run it:
```
java.lang.NoSuchFieldError: F
	at net.minecraft.client.telemetry.TelemetryProperty.hashCode(TelemetryProperty.java:22)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1191)
	at net.minecraft.client.telemetry.events.GameLoadTimesEvent.beginStep(GameLoadTimesEvent.java:40)
	at net.minecraft.client.telemetry.events.GameLoadTimesEvent.beginStep(GameLoadTimesEvent.java:36)
	at net.minecraft.client.main.Main.main(Main.java:57)
```
It appears that something isn't right with this deobfuscated jar since I can use one from VanillaGradle and this problem doesn't occur.

**Comment by Fox2Code** [comment]
Oof, I havent touched this in a long time

**Comment by TalonFloof** [comment]
Yeah I thought so, but I'd thought I would report this anyway

**Comment by Fox2Code** [comment]
I see the issue, it's cause by records, the last time I wrote Repacker, Minecraft wasn't using records yet.

Should be fixed soon! Also please contact me on Discord or Telegram, I like your projects! @TalonFox :3

https://github.com/Fox2Code/FoxLoader | `fox2code` on Discord (Or join [this](https://discord.gg/reedcommunity)) | https://t.me/Fox2Code
